### ISSUE TITLE
当设备离开Wi-Fi网络时，device_tracker的状态从'Home'变为'Away'的延迟大约为2到3分钟

### ISSUE THREAD

**Issue by KaiShaoHoi** [KaiShaoHoi/phicomm_k3#1]
**问题描述:**
设备在离开Wi-Fi网络后，Home Assistant中的device_tracker状态需要等待2到3分钟才能从'Home'变为'Away'。这造成了一定的延迟，影响了系统对设备离家状态的准确性。

**解决思路:**
为了解决这个问题，可以通过创建一个自动化来缩短状态切换的延迟。以下是具体的解决思路：

1. **新建自动化:**
   在Home Assistant中创建一个自动化，该自动化将在设备传感器（如门口的门磁传感器）关闭后触发。

2. **等待1分钟:**
   在自动化中加入一个等待时间的步骤，等待1分钟以确保设备有足够的时间从Wi-Fi网络中断开。

3. **使用ping检查设备状态:**
   在等待后，使用ping命令或其他网络检查工具，检查设备是否仍然在家。如果设备未响应，将其标记为离家状态。

4. **设备标记为离家:**
   如果检测到设备不在家，通过Home Assistant服务或相应组件将device_tracker状态更新为'Away'。

**示例代码:**
```yaml
binary_sensor:
  - platform: ping
    host: your_device_ip
    name: "Device Online"
    scan_interval: 60  # 检查间隔，根据需要调整

automation:
  - alias: "Check Device Away Status"
    trigger:
      platform: state
      entity_id: binary_sensor.door_sensor  # 门口的门磁传感器
      to: "off"  # 传感器关闭触发

    action:
      - delay: "00:01:00"  # 等待1分钟

      - condition: state
        entity_id: binary_sensor.device_online
        state: "off"  # 设备不在线

      - service: device_tracker.see
        data:
          dev_id: your_device
          location_name: "away"  # 更新设备状态为离家

```

请替换示例代码中的"binary_sensor.door_sensor"和"device_tracker.your_device"为你的实际设备和传感器实体。确保你的Home Assistant配置中已经有相应的设备跟踪器和二进制传感器实体。
